/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.it17322.nhom6.views;

import com.github.sarxos.webcam.Webcam;
import com.poly.it17322.nhom6.responses.KhuyenMaiDateRespone;
import com.poly.it17322.nhom6.responses.UserResponse;
import com.poly.it17322.nhom6.services.impl.DangNhapServiceImpl;
import com.poly.it17322.nhom6.services.impl.KhuyenMaiServiceImpl;
import com.poly.it17322.nhom6.utilities.MD5Util;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LiamTrieu
 */
public class FrmMainView extends javax.swing.JFrame {

    private int chosser;
    private UserResponse tkreponse;
    private KhuyenMaiServiceImpl kms = new KhuyenMaiServiceImpl();
    private DangNhapServiceImpl dangNhapService = new DangNhapServiceImpl();

    /**
     * Creates new form frmMain
     */
    public FrmMainView(UserResponse tk) {
        initComponents();
        setLocationRelativeTo(null);
        tkreponse = tk;
        clearChosserListService();
        chosser = 1;
        pnlBanHang.setBackground(new Color(0, 153, 153));
        pnlView.removeAll();
        pnlView.add(new FrmBanHang(tkreponse));
        pnlView.setLayout(new FlowLayout());
        avatar.setIcon(new ImageIcon(getClass().getResource("/avatar/" + tk.getHinhAnh() + ".png")));
        this.pack();
        if (tk.getChucVu() != 0) {
            pnlNhanVien.setVisible(false);
        }
        pnlBaoHanh.setVisible(false);
        jobCheckKM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoiMK = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtnhaplai = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtpassmoi = new javax.swing.JPasswordField();
        txtpasscu = new javax.swing.JPasswordField();
        lbltentk = new javax.swing.JLabel();
        btnDoi = new javax.swing.JButton();
        paneListService = new javax.swing.JPanel();
        pnlBanHang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlSanPham = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlHoaDon = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlKhuyenMai = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlBaoHanh = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlNhanVien = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlKhachHang = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnlThongKe = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        avatar = new com.poly.it17322.nhom6.utilities.ImageAvatar();
        pnlTiltle = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblMini = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnlView = new javax.swing.JPanel();

        DoiMK.setTitle("Đổi mật khẩu");
        DoiMK.setBackground(new java.awt.Color(255, 255, 255));
        DoiMK.setMaximumSize(new java.awt.Dimension(275, 290));
        DoiMK.setMinimumSize(new java.awt.Dimension(275, 290));
        DoiMK.setPreferredSize(new java.awt.Dimension(275, 290));
        DoiMK.setSize(new java.awt.Dimension(275, 290));

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Đổi mật khẩu");
        jLabel17.setMaximumSize(new java.awt.Dimension(240, 40));
        jLabel17.setMinimumSize(new java.awt.Dimension(240, 40));
        jLabel17.setPreferredSize(new java.awt.Dimension(240, 40));

        jLabel18.setText("Tên NV:");

        txtnhaplai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnhaplaiActionPerformed(evt);
            }
        });

        jLabel20.setText("Mật khẩu cũ:");

        jLabel21.setText("Mật khẩu mới:");

        jLabel22.setText("Nhập lại:");

        txtpassmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassmoiActionPerformed(evt);
            }
        });

        txtpasscu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasscuActionPerformed(evt);
            }
        });

        lbltentk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnDoi.setText("Đổi mật khẩu");
        btnDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DoiMKLayout = new javax.swing.GroupLayout(DoiMK.getContentPane());
        DoiMK.getContentPane().setLayout(DoiMKLayout);
        DoiMKLayout.setHorizontalGroup(
            DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DoiMKLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpassmoi))
                    .addGroup(DoiMKLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnhaplai))
                    .addGroup(DoiMKLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltentk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DoiMKLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpasscu))
                    .addComponent(btnDoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        DoiMKLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel18, jLabel20, jLabel21, jLabel22});

        DoiMKLayout.setVerticalGroup(
            DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lbltentk, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtpasscu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtpassmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtnhaplai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDoi)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        DoiMKLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbltentk, txtnhaplai, txtpasscu, txtpassmoi});

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý cửa hàng điện thoại");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        paneListService.setBackground(new java.awt.Color(0, 123, 123));
        paneListService.setMaximumSize(new java.awt.Dimension(200, 690));
        paneListService.setMinimumSize(new java.awt.Dimension(200, 690));
        paneListService.setPreferredSize(new java.awt.Dimension(200, 690));

        pnlBanHang.setBackground(new java.awt.Color(0, 123, 123));
        pnlBanHang.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlBanHang.setMinimumSize(new java.awt.Dimension(200, 50));
        pnlBanHang.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBanHangMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(30, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(30, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Bán hàng");
        jLabel2.setMaximumSize(new java.awt.Dimension(110, 50));
        jLabel2.setMinimumSize(new java.awt.Dimension(110, 50));
        jLabel2.setPreferredSize(new java.awt.Dimension(110, 50));

        javax.swing.GroupLayout pnlBanHangLayout = new javax.swing.GroupLayout(pnlBanHang);
        pnlBanHang.setLayout(pnlBanHangLayout);
        pnlBanHangLayout.setHorizontalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanHangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBanHangLayout.setVerticalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBanHangLayout.createSequentialGroup()
                .addGroup(pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlSanPham.setBackground(new java.awt.Color(0, 123, 123));
        pnlSanPham.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlSanPham.setMinimumSize(new java.awt.Dimension(200, 50));
        pnlSanPham.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSanPhamMouseExited(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/product.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(30, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(30, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(30, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Sản phẩm");
        jLabel4.setMaximumSize(new java.awt.Dimension(110, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(110, 50));
        jLabel4.setPreferredSize(new java.awt.Dimension(110, 50));

        javax.swing.GroupLayout pnlSanPhamLayout = new javax.swing.GroupLayout(pnlSanPham);
        pnlSanPham.setLayout(pnlSanPhamLayout);
        pnlSanPhamLayout.setHorizontalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSanPhamLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSanPhamLayout.setVerticalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSanPhamLayout.createSequentialGroup()
                .addGroup(pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlHoaDon.setBackground(new java.awt.Color(0, 123, 123));
        pnlHoaDon.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlHoaDon.setMinimumSize(new java.awt.Dimension(200, 50));
        pnlHoaDon.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHoaDonMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(30, 50));
        jLabel5.setMinimumSize(new java.awt.Dimension(30, 50));
        jLabel5.setPreferredSize(new java.awt.Dimension(30, 50));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Hóa đơn");
        jLabel6.setMaximumSize(new java.awt.Dimension(110, 50));
        jLabel6.setMinimumSize(new java.awt.Dimension(110, 50));
        jLabel6.setPreferredSize(new java.awt.Dimension(110, 50));

        javax.swing.GroupLayout pnlHoaDonLayout = new javax.swing.GroupLayout(pnlHoaDon);
        pnlHoaDon.setLayout(pnlHoaDonLayout);
        pnlHoaDonLayout.setHorizontalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pnlHoaDonLayout.setVerticalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHoaDonLayout.createSequentialGroup()
                .addGroup(pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlKhuyenMai.setBackground(new java.awt.Color(0, 123, 123));
        pnlKhuyenMai.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlKhuyenMai.setMinimumSize(new java.awt.Dimension(200, 50));
        pnlKhuyenMai.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKhuyenMaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKhuyenMaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKhuyenMaiMouseExited(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sale.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(30, 50));
        jLabel7.setMinimumSize(new java.awt.Dimension(30, 50));
        jLabel7.setPreferredSize(new java.awt.Dimension(30, 50));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Khuyến mại");
        jLabel8.setMaximumSize(new java.awt.Dimension(110, 50));
        jLabel8.setMinimumSize(new java.awt.Dimension(110, 50));
        jLabel8.setPreferredSize(new java.awt.Dimension(110, 50));

        javax.swing.GroupLayout pnlKhuyenMaiLayout = new javax.swing.GroupLayout(pnlKhuyenMai);
        pnlKhuyenMai.setLayout(pnlKhuyenMaiLayout);
        pnlKhuyenMaiLayout.setHorizontalGroup(
            pnlKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhuyenMaiLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pnlKhuyenMaiLayout.setVerticalGroup(
            pnlKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhuyenMaiLayout.createSequentialGroup()
                .addGroup(pnlKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlBaoHanh.setBackground(new java.awt.Color(0, 123, 123));
        pnlBaoHanh.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlBaoHanh.setMinimumSize(new java.awt.Dimension(200, 50));
        pnlBaoHanh.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlBaoHanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBaoHanhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBaoHanhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBaoHanhMouseExited(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/baohanh.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(30, 50));
        jLabel9.setMinimumSize(new java.awt.Dimension(30, 50));
        jLabel9.setPreferredSize(new java.awt.Dimension(30, 50));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Bảo hành");
        jLabel10.setMaximumSize(new java.awt.Dimension(110, 50));
        jLabel10.setMinimumSize(new java.awt.Dimension(110, 50));
        jLabel10.setPreferredSize(new java.awt.Dimension(110, 50));

        javax.swing.GroupLayout pnlBaoHanhLayout = new javax.swing.GroupLayout(pnlBaoHanh);
        pnlBaoHanh.setLayout(pnlBaoHanhLayout);
        pnlBaoHanhLayout.setHorizontalGroup(
            pnlBaoHanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaoHanhLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pnlBaoHanhLayout.setVerticalGroup(
            pnlBaoHanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaoHanhLayout.createSequentialGroup()
                .addGroup(pnlBaoHanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlNhanVien.setBackground(new java.awt.Color(0, 123, 123));
        pnlNhanVien.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlNhanVien.setMinimumSize(new java.awt.Dimension(200, 50));
        pnlNhanVien.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseExited(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nhanvien.png"))); // NOI18N
        jLabel11.setMaximumSize(new java.awt.Dimension(30, 50));
        jLabel11.setMinimumSize(new java.awt.Dimension(30, 50));
        jLabel11.setPreferredSize(new java.awt.Dimension(30, 50));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Nhân viên");
        jLabel12.setMaximumSize(new java.awt.Dimension(110, 50));
        jLabel12.setMinimumSize(new java.awt.Dimension(110, 50));
        jLabel12.setPreferredSize(new java.awt.Dimension(110, 50));

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhanVienLayout.createSequentialGroup()
                .addGroup(pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlKhachHang.setBackground(new java.awt.Color(0, 123, 123));
        pnlKhachHang.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlKhachHang.setMinimumSize(new java.awt.Dimension(200, 50));
        pnlKhachHang.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKhachHangMouseExited(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account.png"))); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(30, 50));
        jLabel13.setMinimumSize(new java.awt.Dimension(30, 50));
        jLabel13.setPreferredSize(new java.awt.Dimension(30, 50));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Khách Hàng");
        jLabel14.setMaximumSize(new java.awt.Dimension(110, 50));
        jLabel14.setMinimumSize(new java.awt.Dimension(110, 50));
        jLabel14.setPreferredSize(new java.awt.Dimension(110, 50));

        javax.swing.GroupLayout pnlKhachHangLayout = new javax.swing.GroupLayout(pnlKhachHang);
        pnlKhachHang.setLayout(pnlKhachHangLayout);
        pnlKhachHangLayout.setHorizontalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhachHangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlKhachHangLayout.setVerticalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhachHangLayout.createSequentialGroup()
                .addGroup(pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlThongKe.setBackground(new java.awt.Color(0, 123, 123));
        pnlThongKe.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlThongKe.setMinimumSize(new java.awt.Dimension(200, 50));
        pnlThongKe.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseExited(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongke.png"))); // NOI18N
        jLabel15.setMaximumSize(new java.awt.Dimension(30, 50));
        jLabel15.setMinimumSize(new java.awt.Dimension(30, 50));
        jLabel15.setPreferredSize(new java.awt.Dimension(30, 50));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Thống kê");
        jLabel16.setMaximumSize(new java.awt.Dimension(110, 50));
        jLabel16.setMinimumSize(new java.awt.Dimension(110, 50));
        jLabel16.setPreferredSize(new java.awt.Dimension(110, 50));

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongKeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongKeLayout.createSequentialGroup()
                .addGroup(pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblDangXuat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        lblDangXuat.setText("Đăng xuất");
        lblDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
        });

        avatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avatarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneListServiceLayout = new javax.swing.GroupLayout(paneListService);
        paneListService.setLayout(paneListServiceLayout);
        paneListServiceLayout.setHorizontalGroup(
            paneListServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListServiceLayout.createSequentialGroup()
                .addGroup(paneListServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlSanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBanHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHoaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(paneListServiceLayout.createSequentialGroup()
                .addGroup(paneListServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneListServiceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneListServiceLayout.createSequentialGroup()
                        .addGroup(paneListServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneListServiceLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblDangXuat)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(avatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneListServiceLayout.setVerticalGroup(
            paneListServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListServiceLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(pnlBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(lblDangXuat)
                .addGap(5, 5, 5))
        );

        pnlTiltle.setBackground(new java.awt.Color(0, 102, 102));
        pnlTiltle.setMaximumSize(new java.awt.Dimension(1280, 30));
        pnlTiltle.setMinimumSize(new java.awt.Dimension(1280, 30));
        pnlTiltle.setPreferredSize(new java.awt.Dimension(1280, 30));
        pnlTiltle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTiltleMouseDragged(evt);
            }
        });
        pnlTiltle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTiltleMousePressed(evt);
            }
        });

        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        lblExit.setMaximumSize(new java.awt.Dimension(30, 30));
        lblExit.setMinimumSize(new java.awt.Dimension(30, 30));
        lblExit.setPreferredSize(new java.awt.Dimension(30, 30));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
        });

        lblMini.setForeground(new java.awt.Color(255, 255, 255));
        lblMini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mimus.png"))); // NOI18N
        lblMini.setMaximumSize(new java.awt.Dimension(30, 30));
        lblMini.setMinimumSize(new java.awt.Dimension(30, 30));
        lblMini.setPreferredSize(new java.awt.Dimension(30, 30));
        lblMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMiniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMiniMouseEntered(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Phần mềm quản lý cửa hàng điện thoại");
        jLabel19.setMaximumSize(new java.awt.Dimension(1120, 30));
        jLabel19.setMinimumSize(new java.awt.Dimension(1120, 30));
        jLabel19.setPreferredSize(new java.awt.Dimension(1120, 30));

        javax.swing.GroupLayout pnlTiltleLayout = new javax.swing.GroupLayout(pnlTiltle);
        pnlTiltle.setLayout(pnlTiltleLayout);
        pnlTiltleLayout.setHorizontalGroup(
            pnlTiltleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTiltleLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        pnlTiltleLayout.setVerticalGroup(
            pnlTiltleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTiltleLayout.createSequentialGroup()
                .addGroup(pnlTiltleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTiltleLayout.createSequentialGroup()
                        .addGroup(pnlTiltleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlView.setBackground(new java.awt.Color(255, 255, 255));
        pnlView.setMaximumSize(new java.awt.Dimension(1080, 720));
        pnlView.setMinimumSize(new java.awt.Dimension(1080, 720));
        pnlView.setPreferredSize(new java.awt.Dimension(1080, 720));

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneListService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTiltle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlTiltle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneListService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlView, javax.swing.GroupLayout.PREFERRED_SIZE, 690, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(FrmMainView.ICONIFIED);
    }//GEN-LAST:event_lblMiniMouseClicked

    private void pnlTiltleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTiltleMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_pnlTiltleMouseDragged
    private int xMouse;
    private int yMouse;
    private void pnlTiltleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTiltleMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlTiltleMousePressed

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        lblExit.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblMiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseEntered
        // TODO add your handling code here:
        lblMini.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
    }//GEN-LAST:event_lblMiniMouseEntered

    private void pnlThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseExited
        // TODO add your handling code here:
        if (chosser != 8)
            pnlThongKe.setBackground(new Color(0, 123, 123));
    }//GEN-LAST:event_pnlThongKeMouseExited

    private void pnlThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseEntered
        // TODO add your handling code here:
        pnlThongKe.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        if (chosser != 8)
            pnlThongKe.setBackground(new Color(0, 180, 180));
    }//GEN-LAST:event_pnlThongKeMouseEntered

    private void pnlThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseClicked
        // TODO add your handling code here:
        try {
            Webcam.getDefault().close();
            clearChosserListService();
            chosser = 8;
            pnlThongKe.setBackground(new Color(0, 153, 153));
            pnlView.removeAll();
            pnlView.add(new FrmThongKe());
            pnlView.setLayout(new FlowLayout());
            this.pack();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pnlThongKeMouseClicked

    private void pnlKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhachHangMouseExited
        // TODO add your handling code here:
        if (chosser != 7)
            pnlKhachHang.setBackground(new Color(0, 123, 123));
    }//GEN-LAST:event_pnlKhachHangMouseExited

    private void pnlKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhachHangMouseEntered
        // TODO add your handling code here:
        pnlKhachHang.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        if (chosser != 7)
            pnlKhachHang.setBackground(new Color(0, 180, 180));
    }//GEN-LAST:event_pnlKhachHangMouseEntered

    private void pnlKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhachHangMouseClicked
        // TODO add your handling code here:
        try {
            Webcam.getDefault().close();
            clearChosserListService();
            chosser = 7;
            pnlKhachHang.setBackground(new Color(0, 153, 153));
            pnlView.removeAll();
            pnlView.add(new FrmKhachhang());
            pnlView.setLayout(new FlowLayout());
            this.pack();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pnlKhachHangMouseClicked

    private void pnlNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseExited
        // TODO add your handling code here:
        if (chosser != 6)
            pnlNhanVien.setBackground(new Color(0, 123, 123));
    }//GEN-LAST:event_pnlNhanVienMouseExited

    private void pnlNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseEntered
        // TODO add your handling code here:
        pnlNhanVien.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        if (chosser != 6)
            pnlNhanVien.setBackground(new Color(0, 180, 180));
    }//GEN-LAST:event_pnlNhanVienMouseEntered

    private void pnlNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseClicked
        // TODO add your handling code here:
        try {
            Webcam.getDefault().close();
            clearChosserListService();
            chosser = 6;
            pnlNhanVien.setBackground(new Color(0, 153, 153));
            pnlView.removeAll();
            pnlView.add(new FrmNhanVien());
            pnlView.setLayout(new FlowLayout());
            this.pack();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pnlNhanVienMouseClicked

    private void pnlKhuyenMaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhuyenMaiMouseExited
        // TODO add your handling code here:
        if (chosser != 4)
            pnlKhuyenMai.setBackground(new Color(0, 123, 123));
    }//GEN-LAST:event_pnlKhuyenMaiMouseExited

    private void pnlKhuyenMaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhuyenMaiMouseEntered
        // TODO add your handling code here:
        pnlKhuyenMai.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        if (chosser != 4)
            pnlKhuyenMai.setBackground(new Color(0, 180, 180));
    }//GEN-LAST:event_pnlKhuyenMaiMouseEntered

    private void pnlKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhuyenMaiMouseClicked
        // TODO add your handling code here:
        try {
            Webcam.getDefault().close();
            clearChosserListService();
            chosser = 4;
            pnlKhuyenMai.setBackground(new Color(0, 153, 153));
            pnlView.removeAll();
            pnlView.add(tkreponse.getChucVu() == 0 ? new FrmQuanLyKhuyenMai() : new FrmNhanVienKhuyenMai());
            pnlView.setLayout(new FlowLayout());
            this.pack();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pnlKhuyenMaiMouseClicked

    private void pnlHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHoaDonMouseExited
        // TODO add your handling code here:
        if (chosser != 3)
            pnlHoaDon.setBackground(new Color(0, 123, 123));
    }//GEN-LAST:event_pnlHoaDonMouseExited

    private void pnlHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHoaDonMouseEntered
        // TODO add your handling code here:
        pnlHoaDon.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        if (chosser != 3)
            pnlHoaDon.setBackground(new Color(0, 180, 180));
    }//GEN-LAST:event_pnlHoaDonMouseEntered

    private void pnlHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHoaDonMouseClicked
        // TODO add your handling code here:
        try {
            Webcam.getDefault().close();
            clearChosserListService();
            chosser = 3;
            pnlHoaDon.setBackground(new Color(0, 153, 153));
            pnlView.removeAll();
            pnlView.add(new FrmHoaDon());
            pnlView.setLayout(new FlowLayout());
            this.pack();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pnlHoaDonMouseClicked

    private void pnlSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMouseExited
        // TODO add your handling code here:
        if (chosser != 2)
            pnlSanPham.setBackground(new Color(0, 123, 123));
    }//GEN-LAST:event_pnlSanPhamMouseExited

    private void pnlSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMouseEntered
        // TODO add your handling code here:
        pnlSanPham.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        if (chosser != 2)
            pnlSanPham.setBackground(new Color(0, 180, 180));
    }//GEN-LAST:event_pnlSanPhamMouseEntered

    private void pnlSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMouseClicked
        // TODO add your handling code here:
        try {
            Webcam.getDefault().close();
            clearChosserListService();
            chosser = 2;
            pnlSanPham.setBackground(new Color(0, 153, 153));
            pnlView.removeAll();
            pnlView.add(tkreponse.getChucVu() == 0 ? new FrmQuanLySanPham() : new FrmNhanVienSanPham());
            pnlView.setLayout(new FlowLayout());
            this.pack();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pnlSanPhamMouseClicked

    private void pnlBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanHangMouseExited
        // TODO add your handling code here:
        if (chosser != 1)
            pnlBanHang.setBackground(new Color(0, 123, 123));
    }//GEN-LAST:event_pnlBanHangMouseExited

    private void pnlBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanHangMouseEntered
        // TODO add your handling code here:
        pnlBanHang.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        if (chosser != 1)
            pnlBanHang.setBackground(new Color(0, 180, 180));
    }//GEN-LAST:event_pnlBanHangMouseEntered

    private void pnlBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanHangMouseClicked
        // TODO add your handling code here:
        try {
            clearChosserListService();
            chosser = 1;
            pnlBanHang.setBackground(new Color(0, 153, 153));
            pnlView.removeAll();
            pnlView.add(new FrmBanHang(tkreponse));
            pnlView.setLayout(new FlowLayout());
            this.pack();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pnlBanHangMouseClicked

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn đăng xuất") == JOptionPane.YES_OPTION) {
            this.dispose();
            new FrmDangNhap().setVisible(true);
            return;
        }
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void pnlBaoHanhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBaoHanhMouseExited
        // TODO add your handling code here:
        if (chosser != 5)
            pnlBaoHanh.setBackground(new Color(0, 123, 123));
    }//GEN-LAST:event_pnlBaoHanhMouseExited

    private void pnlBaoHanhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBaoHanhMouseEntered
        // TODO add your handling code here:
        pnlBaoHanh.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        if (chosser != 5)
            pnlBaoHanh.setBackground(new Color(0, 180, 180));
    }//GEN-LAST:event_pnlBaoHanhMouseEntered

    private void pnlBaoHanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBaoHanhMouseClicked
        // TODO add your handling code here:
        try {
            Webcam.getDefault().close();
            clearChosserListService();
            chosser = 5;
            pnlBaoHanh.setBackground(new Color(0, 153, 153));
            pnlView.removeAll();
            pnlView.add(new FrmBaoHanh());
            pnlView.setLayout(new FlowLayout());
            this.pack();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pnlBaoHanhMouseClicked

    private void txtnhaplaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnhaplaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnhaplaiActionPerformed

    private void txtpassmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassmoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassmoiActionPerformed

    private void txtpasscuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasscuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasscuActionPerformed

    private void avatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avatarMouseClicked
        // TODO add your handling code here:
        DoiMK.setVisible(true);
        DoiMK.setLocationRelativeTo(null);
        lbltentk.setText(tkreponse.getHoTen());
        txtnhaplai.setText("");
        txtpasscu.setText("");
        txtpassmoi.setText("");
    }//GEN-LAST:event_avatarMouseClicked

    private void btnDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiActionPerformed
        // TODO add your handling code here:
        try {
            if (MD5Util.md5EnCode(String.valueOf(txtpasscu.getPassword())).equalsIgnoreCase(tkreponse.getMatKhau())) {
                if (String.valueOf(txtpassmoi.getPassword()).trim().length() < 8) {
                    JOptionPane.showMessageDialog(this, "Mật khẩu trên 8 ký tự");
                } else {
                    if (String.valueOf(txtpassmoi.getPassword()).equals(String.valueOf(txtnhaplai.getPassword()))) {
                        try {
                            String password = MD5Util.md5EnCode(String.valueOf(txtpassmoi.getPassword()).trim());
                            if (dangNhapService.resetPass(password, tkreponse.getMail())) {
                                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
                                DoiMK.setVisible(false);
                            } else {
                                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thất bại");
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, "Hệ thống đang bận");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "2 Mật khẩu không trùng khớp");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Mật khẩu không chính xác");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame DoiMK;
    private com.poly.it17322.nhom6.utilities.ImageAvatar avatar;
    private javax.swing.JButton btnDoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMini;
    private javax.swing.JLabel lbltentk;
    private javax.swing.JPanel paneListService;
    private javax.swing.JPanel pnlBanHang;
    private javax.swing.JPanel pnlBaoHanh;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JPanel pnlKhuyenMai;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlSanPham;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPanel pnlTiltle;
    private javax.swing.JPanel pnlView;
    private javax.swing.JPasswordField txtnhaplai;
    private javax.swing.JPasswordField txtpasscu;
    private javax.swing.JPasswordField txtpassmoi;
    // End of variables declaration//GEN-END:variables

    private void clearChosserListService() {
        pnlBanHang.setBackground(new Color(0, 123, 123));
        pnlSanPham.setBackground(new Color(0, 123, 123));
        pnlHoaDon.setBackground(new Color(0, 123, 123));
        pnlKhuyenMai.setBackground(new Color(0, 123, 123));
        pnlBaoHanh.setBackground(new Color(0, 123, 123));
        pnlNhanVien.setBackground(new Color(0, 123, 123));
        pnlKhachHang.setBackground(new Color(0, 123, 123));
        pnlThongKe.setBackground(new Color(0, 123, 123));
    }

    private void jobCheckKM() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    List<KhuyenMaiDateRespone> lstKM = kms.getListDate();
                    for (KhuyenMaiDateRespone s : lstKM) {
                        int resultBD = LocalDateTime.now().compareTo(s.getNgayBD().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime());
                        int resultKT = LocalDateTime.now().compareTo(s.getNgayKT().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime());
                        if (resultBD < 0) {
                            kms.updateTTKM(0, s.getId());
                        } else {
                            if (resultKT >= 0) {
                                kms.updateTTKM(2, s.getId());
                            } else {
                                kms.updateTTKM(1, s.getId());
                            }
                        }
                    }
                    try {
                        Thread.sleep(5000);
                    } catch (Exception e) {
                    }
                }
            }
        }.start();
    }
}
