/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.it17322.nhom6.views;

import com.poly.it17322.nhom6.responses.KhuyenMaiResponse;
import com.poly.it17322.nhom6.responses.SanPhamBanHangResponse;
import com.poly.it17322.nhom6.services.impl.KhuyenMaiServiceImpl;
import com.poly.it17322.nhom6.utilities.ScrollBarCustom;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LiamTrieu
 */
public class FrmQuanLyKhuyenMai extends javax.swing.JPanel {

    private DefaultTableModel dtm = new DefaultTableModel();
    private List<KhuyenMaiResponse> lstKM = new ArrayList<>();
    private List<SanPhamBanHangResponse> lstSP = new ArrayList<>();
    private List<SanPhamBanHangResponse> lstSPKM = new ArrayList<>();
    private KhuyenMaiServiceImpl kms = new KhuyenMaiServiceImpl();
    private int indexKM = -1;

    /**
     * Creates new form frmBanHang
     */
    public FrmQuanLyKhuyenMai() {
        initComponents();
        designTable();
        filltoTableKM();
        filltoTableSP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboTrangThai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuyenmai = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtSearchKM = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtTimSP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnselect1 = new javax.swing.JButton();
        cboSanPham = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        btnselect2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtNBD = new com.github.lgooddatepicker.components.DateTimePicker();
        txtNKT = new com.github.lgooddatepicker.components.DateTimePicker();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPhamKM = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtSearchSP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnselect = new javax.swing.JButton();
        cboLoai = new javax.swing.JComboBox<>();
        txtGiaTri = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblMa = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2), "Danh sách mã khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sắp diễn ra", "Đang diễn ra", "Đã kết thúc", "Tất cả" }));
        cboTrangThai.setSelectedIndex(3);
        cboTrangThai.setBackground(new java.awt.Color(0, 102, 102));
        cboTrangThai.setFocusable(false);
        cboTrangThai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboTrangThai.setForeground(new java.awt.Color(255, 255, 255));
        cboTrangThai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTrangThaiItemStateChanged(evt);
            }
        });

        tblKhuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Ngày bắt đầu", "Ngày kết thúc", "Giá trị", "Trạng thái", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhuyenmai.setFillsViewportHeight(true);
        tblKhuyenmai.setRowHeight(20);
        tblKhuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenmaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhuyenmai);
        if (tblKhuyenmai.getColumnModel().getColumnCount() > 0) {
            tblKhuyenmai.getColumnModel().getColumn(6).setMinWidth(25);
            tblKhuyenmai.getColumnModel().getColumn(6).setPreferredWidth(25);
            tblKhuyenmai.getColumnModel().getColumn(6).setMaxWidth(25);
        }

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txtSearchKM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSearchKM.setBorder(null);
        txtSearchKM.setCaretColor(new java.awt.Color(0, 102, 102));
        txtSearchKM.setForeground(new java.awt.Color(0, 102, 102));
        txtSearchKM.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchKMCaretUpdate(evt);
            }
        });
        txtSearchKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchKMActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_banhang.png"))); // NOI18N
        jLabel7.setBackground(new java.awt.Color(0, 102, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtSearchKM, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtSearchKM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/endkm.png"))); // NOI18N
        btnXoa.setText("Kết thúc");
        btnXoa.setBackground(new java.awt.Color(255, 0, 0));
        btnXoa.setFocusable(false);
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        txtTimSP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTimSP.setBorder(null);
        txtTimSP.setCaretColor(new java.awt.Color(0, 102, 102));
        txtTimSP.setForeground(new java.awt.Color(0, 102, 102));
        txtTimSP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimSPCaretUpdate(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_banhang.png"))); // NOI18N
        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(txtTimSP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel9))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtTimSP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btnselect1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/selectsp.png"))); // NOI18N
        btnselect1.setText("Chọn hết");
        btnselect1.setBackground(new java.awt.Color(0, 102, 102));
        btnselect1.setFocusPainted(false);
        btnselect1.setFocusable(false);
        btnselect1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnselect1.setForeground(new java.awt.Color(255, 255, 255));
        btnselect1.setMaximumSize(new java.awt.Dimension(120, 30));
        btnselect1.setMinimumSize(new java.awt.Dimension(120, 30));
        btnselect1.setName("chon"); // NOI18N
        btnselect1.setPreferredSize(new java.awt.Dimension(120, 30));
        btnselect1.setToolTipText("");
        btnselect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselect1ActionPerformed(evt);
            }
        });

        cboSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Chưa có khuyết mại", "Đang có khuyến mại" }));
        cboSanPham.setBackground(new java.awt.Color(0, 102, 102));
        cboSanPham.setFocusable(false);
        cboSanPham.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboSanPham.setForeground(new java.awt.Color(255, 255, 255));
        cboSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSanPhamActionPerformed(evt);
            }
        });

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Khuyến mại", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.setFillsViewportHeight(true);
        jScrollPane3.setViewportView(tblSanPham);
        if (tblSanPham.getColumnModel().getColumnCount() > 0) {
            tblSanPham.getColumnModel().getColumn(2).setMinWidth(25);
            tblSanPham.getColumnModel().getColumn(2).setPreferredWidth(25);
            tblSanPham.getColumnModel().getColumn(2).setMaxWidth(25);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cboSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnselect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(346, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnselect1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 293, Short.MAX_VALUE)))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnselect1, cboSanPham});

        btnselect2.setBackground(new java.awt.Color(0, 102, 102));
        btnselect2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnselect2.setForeground(new java.awt.Color(255, 255, 255));
        btnselect2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/selectsp.png"))); // NOI18N
        btnselect2.setText("Chọn hết");
        btnselect2.setToolTipText("");
        btnselect2.setFocusPainted(false);
        btnselect2.setFocusable(false);
        btnselect2.setMaximumSize(new java.awt.Dimension(120, 30));
        btnselect2.setMinimumSize(new java.awt.Dimension(120, 30));
        btnselect2.setName("chon"); // NOI18N
        btnselect2.setPreferredSize(new java.awt.Dimension(120, 30));
        btnselect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselect2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnselect2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(413, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnselect2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(611, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnXoa, cboTrangThai, jPanel5});

        jLabel1.setText("Tên khuyến mại:");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel2.setText("Ngày bắt đầu:");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));

        jLabel3.setText("Ngày kết thúc:");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));

        jLabel4.setText("Loại Khuyến mại:");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));

        jLabel5.setText("Giá trị: ");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));

        txtTen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txtTen.setForeground(new java.awt.Color(0, 102, 102));

        txtNBD.setBackground(new java.awt.Color(255, 255, 255));
        txtNBD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txtNBD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNBD.setForeground(new java.awt.Color(0, 102, 102));

        txtNKT.setBackground(new java.awt.Color(255, 255, 255));
        txtNKT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txtNKT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNKT.setForeground(new java.awt.Color(0, 102, 102));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addspct.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBackground(new java.awt.Color(0, 102, 102));
        btnThem.setFocusable(false);
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/updatekm.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBackground(new java.awt.Color(0, 102, 102));
        btnSua.setFocusable(false);
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clearkh.png"))); // NOI18N
        btnClear.setText("Làm mới");
        btnClear.setBackground(new java.awt.Color(0, 102, 102));
        btnClear.setFocusable(false);
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2), "Sản phẩm áp dụng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        tblSanPhamKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPhamKM.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(tblSanPhamKM);
        if (tblSanPhamKM.getColumnModel().getColumnCount() > 0) {
            tblSanPhamKM.getColumnModel().getColumn(1).setMinWidth(25);
            tblSanPhamKM.getColumnModel().getColumn(1).setPreferredWidth(25);
            tblSanPhamKM.getColumnModel().getColumn(1).setMaxWidth(25);
        }

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtSearchSP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSearchSP.setBorder(null);
        txtSearchSP.setCaretColor(new java.awt.Color(0, 102, 102));
        txtSearchSP.setForeground(new java.awt.Color(0, 102, 102));
        txtSearchSP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchSPCaretUpdate(evt);
            }
        });
        txtSearchSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSPActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_banhang.png"))); // NOI18N
        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtSearchSP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel6))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtSearchSP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btnselect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/uncheck.png"))); // NOI18N
        btnselect.setText("Bỏ chọn");
        btnselect.setBackground(new java.awt.Color(0, 102, 102));
        btnselect.setFocusPainted(false);
        btnselect.setFocusable(false);
        btnselect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnselect.setForeground(new java.awt.Color(255, 255, 255));
        btnselect.setMaximumSize(new java.awt.Dimension(120, 30));
        btnselect.setMinimumSize(new java.awt.Dimension(120, 30));
        btnselect.setName("chon"); // NOI18N
        btnselect.setPreferredSize(new java.awt.Dimension(120, 30));
        btnselect.setToolTipText("");
        btnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnselect, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(347, Short.MAX_VALUE)))
        );

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phần trăm", "Giá tiền" }));
        cboLoai.setBackground(new java.awt.Color(0, 102, 102));
        cboLoai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboLoai.setForeground(new java.awt.Color(255, 255, 255));

        txtGiaTri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtGiaTri.setForeground(new java.awt.Color(0, 102, 102));

        jLabel8.setText("Mã khuyến mại:");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));

        lblMa.setText("...");
        lblMa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMa.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNBD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                            .addComponent(txtNKT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTen))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblMa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 55, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboLoai, jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel8, lblMa, txtGiaTri, txtNBD, txtNKT, txtTen});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClear, btnSua, btnThem});

    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchSPActionPerformed

    private void txtSearchKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKMActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (checkForm()) {
            List<UUID> lsidSP = new ArrayList<>();
            for (int i = 0; i < tblSanPham.getRowCount(); i++) {
                if (Boolean.parseBoolean(tblSanPham.getValueAt(i, 2).toString())) {
                    lsidSP.add(lstSP.get(i).getId());
                }
            }
            if (kms.createKM(getData(), lsidSP)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
            filltoTableKM();
            filltoTableSP();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblKhuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuyenmaiMouseClicked
        // TODO add your handling code here:
        int column = tblKhuyenmai.columnAtPoint(evt.getPoint());
        if (column == 6) {
            return;
        }
        indexKM = tblKhuyenmai.getSelectedRow();
        lblMa.setText(lstKM.get(indexKM).getMa());
        txtTen.setText(lstKM.get(indexKM).getTen());
        txtNBD.setDateTimePermissive(LocalDateTime.ofInstant(lstKM.get(indexKM).getNgayBD().toInstant(), ZoneId.systemDefault()));
        txtNKT.setDateTimePermissive(LocalDateTime.ofInstant(lstKM.get(indexKM).getNgayKT().toInstant(), ZoneId.systemDefault()));
        cboLoai.setSelectedIndex(lstKM.get(indexKM).getLoai());
        txtGiaTri.setText(lstKM.get(indexKM).getGiaTri() + "");
        filltoTableSPKM();
    }//GEN-LAST:event_tblKhuyenmaiMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFrom();
    }//GEN-LAST:event_btnClearActionPerformed

    private void cboTrangThaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTrangThaiItemStateChanged
        // TODO add your handling code here:
        filltoTableKM();
    }//GEN-LAST:event_cboTrangThaiItemStateChanged

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (checkForm()) {
            if (indexKM == -1) {
                JOptionPane.showMessageDialog(this, "Chưa chọn khuyến mại");
                return;
            }
            List<UUID> lsidSPBo = new ArrayList<>();
            List<UUID> lsidSPThem = new ArrayList<>();
            for (int i = 0; i < tblSanPhamKM.getRowCount(); i++) {
                String check = tblSanPhamKM.getValueAt(i, 1).toString();
                if (!Boolean.parseBoolean(check)) {
                    lsidSPBo.add(lstSPKM.get(i).getId());
                }
            }
            for (int i = 0; i < tblSanPham.getRowCount(); i++) {
                String check = tblSanPham.getValueAt(i, 2).toString();
                if (Boolean.parseBoolean(check)) {
                    lsidSPThem.add(lstSP.get(i).getId());
                }
            }
            KhuyenMaiResponse km = getData();
            km.setId(lstKM.get(indexKM).getId());
            if (kms.updateKM(km, lsidSPBo, lsidSPThem)) {
                JOptionPane.showMessageDialog(this, "Update thành công");
            }
            clearFrom();
            filltoTableKM();
            filltoTableSP();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int cout = 0;
        boolean check = false;
        String mess = "Chỉ kết thúc các khuyến mại đang diễn ra";
        try {
            for (int i = 0; i < tblKhuyenmai.getRowCount(); i++) {
                if (Boolean.parseBoolean(tblKhuyenmai.getValueAt(i, 6).toString())) {
                    check = true;
                    if (lstKM.get(i).getTrangThai() == 1) {
                        kms.KTKM(lstKM.get(i).getId());
                        cout++;
                        mess = "Kết thúc " + cout + " khuyến mại thành công";
                    }
                }
            }
        } catch (Exception e) {
            mess = "kết thúc khuyến mại thất bại";
        }
        if (check) {
            JOptionPane.showMessageDialog(this, mess);
            clearFrom();
            filltoTableKM();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectActionPerformed
        // TODO add your handling code here:
        if (btnselect.getText().equals("Chọn hết")) {
            btnselect.setIcon(new ImageIcon(getClass().getResource("/icon/uncheck.png")));
            btnselect.setText("Bỏ chọn");
            for (int i = 0; i < tblSanPhamKM.getRowCount(); i++) {
                tblSanPhamKM.setValueAt(true, i, 1);
            }
        } else {
            btnselect.setIcon(new ImageIcon(getClass().getResource("/icon/selectsp.png")));
            btnselect.setText("Chọn hết");
            for (int i = 0; i < tblSanPhamKM.getRowCount(); i++) {
                tblSanPhamKM.setValueAt(false, i, 1);
            }
        }
    }//GEN-LAST:event_btnselectActionPerformed

    private void btnselect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselect1ActionPerformed
        // TODO add your handling code here:
        if (btnselect1.getText().equals("Chọn hết")) {
            btnselect1.setIcon(new ImageIcon(getClass().getResource("/icon/uncheck.png")));
            btnselect1.setText("Bỏ chọn");
            for (int i = 0; i < tblSanPham.getRowCount(); i++) {
                tblSanPham.setValueAt(true, i, 2);
            }
        } else {
            btnselect1.setIcon(new ImageIcon(getClass().getResource("/icon/selectsp.png")));
            btnselect1.setText("Chọn hết");
            for (int i = 0; i < tblSanPham.getRowCount(); i++) {
                tblSanPham.setValueAt(false, i, 2);
            }
        }
    }//GEN-LAST:event_btnselect1ActionPerformed

    private void cboSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSanPhamActionPerformed
        // TODO add your handling code here:
        filltoTableSP();
    }//GEN-LAST:event_cboSanPhamActionPerformed

    private void txtTimSPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimSPCaretUpdate
        // TODO add your handling code here:
        filltoTableSP();
    }//GEN-LAST:event_txtTimSPCaretUpdate

    private void txtSearchKMCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchKMCaretUpdate
        // TODO add your handling code here:
        filltoTableKM();
    }//GEN-LAST:event_txtSearchKMCaretUpdate

    private void txtSearchSPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchSPCaretUpdate
        // TODO add your handling code here:
        filltoTableSPKM();
    }//GEN-LAST:event_txtSearchSPCaretUpdate

    private void btnselect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselect2ActionPerformed
        // TODO add your handling code here:
        if (btnselect2.getText().equals("Chọn hết")) {
            btnselect2.setIcon(new ImageIcon(getClass().getResource("/icon/uncheck.png")));
            btnselect2.setText("Bỏ chọn");
            for (int i = 0; i < tblKhuyenmai.getRowCount(); i++) {
                tblKhuyenmai.setValueAt(true, i, 6);
            }
        } else {
            btnselect2.setIcon(new ImageIcon(getClass().getResource("/icon/selectsp.png")));
            btnselect2.setText("Chọn hết");
            for (int i = 0; i < tblKhuyenmai.getRowCount(); i++) {
                tblKhuyenmai.setValueAt(false, i, 6);
            }
        }
    }//GEN-LAST:event_btnselect2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnselect;
    private javax.swing.JButton btnselect1;
    private javax.swing.JButton btnselect2;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboSanPham;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMa;
    private javax.swing.JTable tblKhuyenmai;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTable tblSanPhamKM;
    private javax.swing.JTextField txtGiaTri;
    private com.github.lgooddatepicker.components.DateTimePicker txtNBD;
    private com.github.lgooddatepicker.components.DateTimePicker txtNKT;
    private javax.swing.JTextField txtSearchKM;
    private javax.swing.JTextField txtSearchSP;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimSP;
    // End of variables declaration//GEN-END:variables

    private void designTable() {
        tblKhuyenmai.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        tblKhuyenmai.getTableHeader().setBackground(new Color(0, 123, 123));
        tblKhuyenmai.getTableHeader().setForeground(new Color(255, 255, 255));
        tblKhuyenmai.setRowHeight(30);
        tblKhuyenmai.getTableHeader().setPreferredSize(new Dimension(100, 30));
        tblSanPhamKM.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        tblSanPhamKM.getTableHeader().setBackground(new Color(0, 123, 123));
        tblSanPhamKM.getTableHeader().setForeground(new Color(255, 255, 255));
        tblSanPhamKM.setRowHeight(30);
        tblSanPhamKM.getTableHeader().setPreferredSize(new Dimension(100, 30));
        tblSanPham.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        tblSanPham.getTableHeader().setBackground(new Color(0, 123, 123));
        tblSanPham.getTableHeader().setForeground(new Color(255, 255, 255));
        tblSanPham.setRowHeight(30);
        tblSanPham.getTableHeader().setPreferredSize(new Dimension(100, 30));

        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
        jScrollPane2.setVerticalScrollBar(new ScrollBarCustom());
        jScrollPane3.setVerticalScrollBar(new ScrollBarCustom());
    }

    private void filltoTableKM() {
        dtm = (DefaultTableModel) tblKhuyenmai.getModel();
        dtm.setRowCount(0);
        btnselect2.setIcon(new ImageIcon(getClass().getResource("/icon/selectsp.png")));
        btnselect2.setText("Chọn hết");
        lstKM = kms.getList(cboTrangThai.getSelectedIndex(), txtSearchKM.getText());
        for (KhuyenMaiResponse s : lstKM) {
            dtm.addRow(s.toDataRow());
        }
    }

    private void filltoTableSPKM() {
        dtm = (DefaultTableModel) tblSanPhamKM.getModel();
        dtm.setRowCount(0);
        btnselect.setIcon(new ImageIcon(getClass().getResource("/icon/uncheck.png")));
        btnselect.setText("Bỏ chọn");
        lstSPKM = kms.SelectIDSPBYKM(lstKM.get(indexKM).getId(), txtSearchSP.getText());
        for (SanPhamBanHangResponse s : lstSPKM) {
            dtm.addRow(new Object[]{s.getTenSanPham(), true});
        }
    }

    private void filltoTableSP() {
        dtm = (DefaultTableModel) tblSanPham.getModel();
        dtm.setRowCount(0);
        btnselect1.setIcon(new ImageIcon(getClass().getResource("/icon/selectsp.png")));
        btnselect1.setText("Chọn hết");
        lstSP = kms.getAllSp(cboSanPham.getSelectedIndex(), txtTimSP.getText());
        for (SanPhamBanHangResponse s : lstSP) {
            dtm.addRow(new Object[]{s.getTenSanPham(), s.getKhuyenMai(), false});
        }
    }

    private void clearFrom() {
        indexKM = -1;
        tblKhuyenmai.clearSelection();
        lblMa.setText("...");
        txtTen.setText("");
        txtNBD.setDateTimePermissive(null);
        txtNKT.setDateTimePermissive(null);
        cboLoai.setSelectedIndex(0);
        txtGiaTri.setText("");
        btnselect.setIcon(new ImageIcon(getClass().getResource("/icon/uncheck.png")));
        btnselect.setText("Bỏ chọn");
        lstSPKM.clear();
        dtm = (DefaultTableModel) tblSanPhamKM.getModel();
        dtm.setRowCount(0);
        filltoTableSP();
    }

    private KhuyenMaiResponse getData() {
        KhuyenMaiResponse km = new KhuyenMaiResponse();
        km.setTen(txtTen.getText());
        km.setNgayBD(Date.from(txtNBD.getDateTimePermissive().atZone(ZoneId.systemDefault()).toInstant()));
        km.setNgayKT(Date.from(txtNKT.getDateTimePermissive().atZone(ZoneId.systemDefault()).toInstant()));
        km.setLoai(cboLoai.getSelectedIndex());
        km.setGiaTri(Integer.parseInt(txtGiaTri.getText()));
        return km;
    }

    private boolean checkForm() {
        if (txtTen.getText().trim().equals("") || txtNBD.getDateTimePermissive() == null
                || txtNKT.getDateTimePermissive() == null || txtGiaTri.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
            return false;
        }
        if (txtTen.getText().trim().length() > 30) {
            JOptionPane.showMessageDialog(this, "Tên không được quá 30 ký tự");
            return false;
        }
        try {
            Date ngayBD = Date.from(txtNBD.getDateTimePermissive().atZone(ZoneId.systemDefault()).toInstant());
            Date ngayKT = Date.from(txtNKT.getDateTimePermissive().atZone(ZoneId.systemDefault()).toInstant());
            if (ngayKT.compareTo(ngayBD) < 0) {
                JOptionPane.showMessageDialog(this, "Ngày kết thúc phải sau ngày bắt đầu");
                txtNKT.clear();
                return false;
            }
        } catch (Exception e) {
            txtNKT.clear();
            return false;
        }
        if (cboLoai.getSelectedIndex() == 0) {
            try {
                if (Integer.parseInt(txtGiaTri.getText()) > 100) {
                    JOptionPane.showMessageDialog(this, "Không được quá 100%");
                    return false;
                }
                if (Integer.parseInt(txtGiaTri.getText()) <= 0) {
                    JOptionPane.showMessageDialog(this, "Phải lớn hơn 0");
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Giá trị không hợp lệ");
                return false;
            }
        } else {
            try {
                Integer.parseInt(txtGiaTri.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Giá trị không hợp lệ");
                return false;
            }
        }
        return true;
    }
}
